//
//  QuoteKit.swift
//  QuoteKit
//
//  Created by Benjamin Robinson on 3/2/2020.
//  Copyright (c) 2021 Benjamin Robinson
//
//  Licensed under the MIT license.
//

import Foundation

// MARK: - Quote Struct

public struct Quote: Equatable {
    public static func == (lhs: Quote, rhs: Quote) -> Bool {
        return
            lhs.identifier == rhs.identifier &&
            lhs.body == rhs.body &&
            lhs.author == rhs.author
    }
    
    public let author: String
    public let body: String
    public let identifier: Int
    
    public init(author: String, body: String, identifier: Int) {
        self.author = author
        self.body = body
        self.identifier = identifier
    }
}

// MARK: - QuoteProvider

public struct QuoteProvider {
    public static func randomQuote() -> Quote {
        return quotes.randomElement()!
    }
    
    public static let quotes = [
        Quote(author: NSLocalizedString("Farnoosh Brock", comment: "Author"), body: NSLocalizedString("We should start choosing our thoughts like we choose our clothes for the day.", comment: "Quote"), identifier: 0),
        Quote(author: NSLocalizedString("Walt Disney", comment: "Author"), body: NSLocalizedString("The way to get started is to quit talking and begin doing.", comment: "Quote"), identifier: 1),
        Quote(author: NSLocalizedString("Roald Dahl", comment: "Author"), body: NSLocalizedString("If you have good thoughts, they will shine out of your face like sunbeams and you will always look lovely.", comment: "Quote"), identifier: 2),
        Quote(author: NSLocalizedString("Lindsey Vonn", comment: "Author"), body: NSLocalizedString("Life changes very quickly, in a very positive way, if you let it.", comment: "Quote"), identifier: 3),
        Quote(author: NSLocalizedString("Rob Siltanen", comment: "Author"), body: NSLocalizedString("People who are crazy enough to think they can change the world are the ones who do.", comment: "Quote"), identifier: 4),
        Quote(author: NSLocalizedString("Thich Nhat Hanh", comment: "Author"), body: NSLocalizedString("Smile, bre​athe and go slowly.", comment: "Quote"), identifier: 5),
        Quote(author: NSLocalizedString("Reese Witherspoon", comment: "Author"), body: NSLocalizedString("With the right kind of coaching and determination,​ you can accomplish anything.", comment: "Quote"), identifier: 6),
        Quote(author: NSLocalizedString("Deep Roy", comment: "Author"), body: NSLocalizedString("Inspiration comes from within yourself. One has to be positive. When you're positive, good things happen.", comment: "Quote"), identifier: 7),
        Quote(author: NSLocalizedString("Unknown", comment: "Author"), body: NSLocalizedString("An arrow can only be shot by pulling it backwards. When life is dragging you back with difficulties, it means it's going to launch you into something great.", comment: "Quote"), identifier: 8),
        Quote(author: NSLocalizedString("Unknown", comment: "Author"), body: NSLocalizedString("Create the highest, grandest vision possible for your​ life, because you become what you believe", comment: "Quote"), identifier: 9),
        Quote(author: NSLocalizedString("Edwin Eliot", comment: "Author"), body: NSLocalizedString("By being yourself, you put something wonderful in the world that was not there before.", comment: "Quote"), identifier: 10),
        Quote(author: NSLocalizedString("Edlester.com", comment: "Author"), body: NSLocalizedString("When you can't find sunshine, be the sunshine!", comment: "Quote"), identifier: 11),
        Quote(author: NSLocalizedString("Michael Altschuler", comment: "Author"), body: NSLocalizedString("The bad news is time flies. The good news is you're the pilot.", comment: "Quote"), identifier: 12),
        Quote(author: NSLocalizedString("Ralph Waldo Emerson", comment: "Author"), body: NSLocalizedString("Don’t be pushed by your problems. Be led by your dreams.", comment: "Quote"), identifier: 13),
        Quote(author: NSLocalizedString("Dr Henry Link", comment: "Author"), body: NSLocalizedString("We generate fears while we sit. We overcome them by action.", comment: "Quote"), identifier: 14),
        Quote(author: NSLocalizedString("Maya Angelou", comment: "Author"), body: NSLocalizedString("You may not control all the events that happen to you, but you can decide not to be reduced by them.", comment: "Quote"), identifier: 15),
        Quote(author: NSLocalizedString("ilovemylsi.com", comment: "Author"), body: NSLocalizedString("Don't forget you're human. It's okay to have a meltdown. Just don't unpack and live there. Cry it out. Then refocus on where you're headed.", comment: "Quote"), identifier: 16),
        Quote(author: NSLocalizedString("Henry Ward Beecher", comment: "Author"), body: NSLocalizedString("Every tomorrow has two handles. We can take hold of it with the handle of anxiety or the handle of faith.", comment: "Quote"), identifier: 17),
        Quote(author: NSLocalizedString("Eleanor Roosevelt", comment: "Author"), body: NSLocalizedString("You must do things you think you cannot do.", comment: "Quote"), identifier: 18),
        Quote(author: NSLocalizedString("Oprah Winfrey", comment: "Author"), body: NSLocalizedString("If you look at what you have in life, you'll always have more.", comment: "Quote"), identifier: 19),
        Quote(author: NSLocalizedString("George Eliot", comment: "Author"), body: NSLocalizedString("It is never too late to be what you might have been.", comment: "Quote"), identifier: 20),
        Quote(author: NSLocalizedString("Albert Einstein", comment: "Author"), body: NSLocalizedString("Learn from yesterday, live for today, hope for tomorrow.", comment: "Quote"), identifier: 21),
        Quote(author: NSLocalizedString("C. S. Lewis", comment: "Author"), body: NSLocalizedString("You are never too old to set another goal or to dream a new dream.", comment: "Quote"), identifier: 22),
        Quote(author: NSLocalizedString("Will Rogers", comment: "Author"), body: NSLocalizedString("Don't let yesterday take up too much of today.", comment: "Quote"), identifier: 23),
        Quote(author: NSLocalizedString("Mandy Hale", comment: "Author"), body: NSLocalizedString("It’s OKAY to be scared. Being scared means you’re about to do something really, really brave.", comment: "Quote"), identifier: 24),
        Quote(author: NSLocalizedString("Henry Ford", comment: "Author"), body: NSLocalizedString("Whether you think you can or you think you can't, you are right.", comment: "Quote"), identifier: 25),
        Quote(author: NSLocalizedString("Mahatma Gandhi", comment: "Author"), body: NSLocalizedString("Be the change you wish to see in the world.", comment: "Quote"), identifier: 26),
        Quote(author: NSLocalizedString("Zig Ziglar", comment: "Author"), body: NSLocalizedString("You don't have to be great to start but you have to start to be great.", comment: "Quote"), identifier: 27),
        Quote(author: NSLocalizedString("Helen Keller", comment: "Author"), body: NSLocalizedString("Keep your face to the sunshine and you cannot see a shadow.", comment: "Quote"), identifier: 28),
        Quote(author: NSLocalizedString("Michelle Obama", comment: "Author"), body: NSLocalizedString("One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals.", comment: "Quote"), identifier: 29),
        Quote(author: NSLocalizedString("Mandy Hale", comment: "Author"), body: NSLocalizedString("You don't always need a plan. Sometimes you just need to breathe, trust, let go and see what happens.", comment: "Quote"), identifier: 30),
        Quote(author: NSLocalizedString("Bookafide", comment: "Author"), body: NSLocalizedString("Happiness is not the absence of problems, it's the ability to deal with them.", comment: "Quote"), identifier: 31),
        Quote(author: NSLocalizedString("Eckhart Tolle", comment: "Author"), body: NSLocalizedString("You have a treasure within you that is infinitely greater than anything the world can offer.", comment: "Quote"), identifier: 32),
        Quote(author: NSLocalizedString("Dr Seuss", comment: "Author"), body: NSLocalizedString("Don't cry because it's over, smile because it happened.", comment: "Quote"), identifier: 33),
        Quote(author: NSLocalizedString("Dan Millman", comment: "Author"), body: NSLocalizedString("You don’t have to control your thoughts. You just have to stop letting them control you.", comment: "Quote"), identifier: 34),
        Quote(author: NSLocalizedString("John Wooden", comment: "Author"), body: NSLocalizedString("Things work out best for those who make the best of how things work out.", comment: "Quote"), identifier: 35),
        Quote(author: NSLocalizedString("Edlester.com", comment: "Author"), body: NSLocalizedString("Little by little, day by day, what is meant for you will find its way.", comment: "Quote"), identifier: 36),
        Quote(author: NSLocalizedString("Franlin D Roosevelt", comment: "Author"), body: NSLocalizedString("The only limit to our realization of tomorrow will be our doubts of today.", comment: "Quote"), identifier: 37),
        Quote(author: NSLocalizedString("Neil Barringham", comment: "Author"), body: NSLocalizedString("The grass is greener where you water it.", comment: "Quote"), identifier: 38),
        Quote(author: NSLocalizedString("Martin Luther King Jr", comment: "Author"), body: NSLocalizedString("If you can’t fly then run, if you can’t run then walk, if you can’t walk then crawl, but whatever you do you have to keep moving forward.", comment: "Quote"), identifier: 39),
        Quote(author: NSLocalizedString("Ella Fitzgerald", comment: "Author"), body: NSLocalizedString("It isn't where you came from. It's where you're going that counts.", comment: "Quote"), identifier: 40),
        Quote(author: NSLocalizedString("Ali Ibn Abi Talib", comment: "Author"), body: NSLocalizedString("Do not let your difficulties fill you with anxiety; after all,​ it is only in the darkest nights that stars shine more brightly.", comment: "Quote"), identifier: 41),
        Quote(author: NSLocalizedString("John Barrymore", comment: "Author"), body: NSLocalizedString("Happiness often sneaks in through a door you didn't know you left open.", comment: "Quote"), identifier: 42),
        Quote(author: NSLocalizedString("Brian Tracy", comment: "Author"), body: NSLocalizedString("Make your life a masterpiece; imagine no limitations on what you can be, have or do.", comment: "Quote"), identifier: 43),
        Quote(author: NSLocalizedString("Joshua J. Marine", comment: "Author"), body: NSLocalizedString("Challenges are what makes life interesting and overcoming them is what makes life meaningful.", comment: "Quote"), identifier: 44),
        Quote(author: NSLocalizedString("Hazrat Inayat Khan", comment: "Author"), body: NSLocalizedString("Some people look for a beautiful place. Others make a place beautiful.", comment: "Quote"), identifier: 45),
        Quote(author: NSLocalizedString("Maya Angelou", comment: "Author"), body: NSLocalizedString("Try to be a rainbow in someone else's cloud.", comment: "Quote"), identifier: 46),
        Quote(author: NSLocalizedString("Mandy Hale", comment: "Author"), body: NSLocalizedString("Happiness is letting go of what you think your life is supposed to look like and celebrating it for everything that it is.", comment: "Quote"), identifier: 47),
        Quote(author: NSLocalizedString("Malala Yousafzai", comment: "Author"), body: NSLocalizedString("Let us make our future now, and let us make our dreams tomorrow's reality.", comment: "Quote"), identifier: 48),
        Quote(author: NSLocalizedString("Joseph Campbell", comment: "Author"), body: NSLocalizedString("We must be willing to let go of the life we planned so as to have the life that is waiting for us.", comment: "Quote"), identifier: 49),
        Quote(author: NSLocalizedString("Robin Williams", comment: "Author"), body: NSLocalizedString("No matter what people tell you, words and ideas can change the world.", comment: "Quote"), identifier: 50),
        Quote(author: NSLocalizedString("Meghan Markle", comment: "Author"), body: NSLocalizedString("You are enough just as you are.", comment: "Quote"), identifier: 51),
        Quote(author: NSLocalizedString("Albert Einstein", comment: "Author"), body: NSLocalizedString("Life is like riding a bicycle. To keep your balance, you must keep moving.", comment: "Quote"), identifier: 52),
        Quote(author: NSLocalizedString("Ella Fitzgerald", comment: "Author"), body: NSLocalizedString("Just don't give up trying to do what you really want to do. Where there is love and inspiration, I don't think you can go wrong.", comment: "Quote"), identifier: 53),
        Quote(author: NSLocalizedString("William W. Purkey", comment: "Author"), body: NSLocalizedString("You've gotta dance like there's nobody watching, love like you'll never be hurt, sing like there's nobody listening, and live like it's heaven on earth.", comment: "Quote"), identifier: 54),
        Quote(author: NSLocalizedString("Nicole Kidman", comment: "Author"), body: NSLocalizedString("Life has got all those twists and turns. You've got to hold on tight and off you go.", comment: "Quote"), identifier: 55),
        Quote(author: NSLocalizedString("Napolean Hill", comment: "Author"), body: NSLocalizedString("Don't wait. The time will never be just right.", comment: "Quote"), identifier: 56),
        Quote(author: NSLocalizedString("Audrey Hepurn", comment: "Author"), body: NSLocalizedString("Nothing is impossible. The word itself says 'I'm possible!'", comment: "Quote"), identifier: 57),
        Quote(author: NSLocalizedString("Mae Jemison", comment: "Author"), body: NSLocalizedString("Never limit yourself because of others' limited imagination​; never limit others because of your own limited imagination.", comment: "Quote"), identifier: 58),
        Quote(author: NSLocalizedString("Serena Williams", comment: "Author"), body: NSLocalizedString("A champion is defined not by their wins but by how they can recover when they fall.", comment: "Quote"), identifier: 59),
        Quote(author: NSLocalizedString("S. Anja", comment: "Author"), body: NSLocalizedString("The sun is a daily reminder that we too can rise again from the darkness, that we too can shine our own light.", comment: "Quote"), identifier: 60),
        Quote(author: NSLocalizedString("Wayne Dyer", comment: "Author"), body: NSLocalizedString("You can’t always control what goes on outside. But you can always control what goes on inside.", comment: "Quote"), identifier: 61),
        Quote(author: NSLocalizedString("Oscar Wilde", comment: "Author"), body: NSLocalizedString("When it rains, look for rainbows. When it's dark, look for stars.", comment: "Quote"), identifier: 62),
        Quote(author: NSLocalizedString("Maya Angelou", comment: "Author"), body: NSLocalizedString("We may encounter many defeats, but we must not be defeated.", comment: "Quote"), identifier: 63),
        Quote(author: NSLocalizedString("Mother Teresa", comment: "Author"), body: NSLocalizedString("Spread love everywhere you go.", comment: "Quote"), identifier: 64),
        Quote(author: NSLocalizedString("Vince Lombardi", comment: "Author"), body: NSLocalizedString("It's not whether you get knocked down, it's whether you get up.", comment: "Quote"), identifier: 65),
        Quote(author: NSLocalizedString("Winston Churchill", comment: "Author"), body: NSLocalizedString("Success consists of going from failure to failure without loss of enthusiasm.", comment: "Quote"), identifier: 66),
        Quote(author: NSLocalizedString("Winston Churchill", comment: "Author"), body: NSLocalizedString("Success is not final, failure is not fatal: It is the courage to continue that counts", comment: "Quote"), identifier: 67),
        Quote(author: NSLocalizedString("Hamlet, Shakespeare", comment: "Author"), body: NSLocalizedString("There is nothing either good or bad, but thinking makes it so.", comment: "Quote"), identifier: 68),
        Quote(author: NSLocalizedString("Pablo Picaso", comment: "Author"), body: NSLocalizedString("I'm always doing things I can't do. That's how I get to do them.", comment: "Quote"), identifier: 69),
        Quote(author: NSLocalizedString("James Allen", comment: "Author"), body: NSLocalizedString("The dreamers are the saviours of the world", comment: "Quote"), identifier: 70),
        Quote(author: NSLocalizedString("Confucious", comment: "Author"), body: NSLocalizedString("Everything has great beauty, but not everyone sees it.", comment: "Quote"), identifier: 71),
        Quote(author: NSLocalizedString("Albert Camus", comment: "Author"), body: NSLocalizedString("In the midst of winter, I found there was within me an invincible summer.", comment: "Quote"), identifier: 72),
        Quote(author: NSLocalizedString("Mary Engelbreit", comment: "Author"), body: NSLocalizedString("Life's too mysterious to take too serious.", comment: "Quote"), identifier: 73),
        Quote(author: NSLocalizedString("Osho", comment: "Author"), body: NSLocalizedString("A little foolishness, enough to enjoy life, and a little wisdom to avoid errors, that will do.", comment: "Quote"), identifier: 74),
        Quote(author: NSLocalizedString("Gilbert Chesterton", comment: "Author"), body: NSLocalizedString("Without the rain there would be no rainbows.", comment: "Quote"), identifier: 75),
        Quote(author: NSLocalizedString("Maxime Legace", comment: "Author"), body: NSLocalizedString("Challenges, failures, defeats and ultimately, progress, are what make your life worthwhile.", comment: "Quote"), identifier: 76),
        Quote(author: NSLocalizedString("Brian Tracy", comment: "Author"), body: NSLocalizedString("Optimism is the one quality more associated with success and happiness than any other.", comment: "Quotes"), identifier: 77),
        Quote(author: NSLocalizedString("Steve Jobs", comment: "Author"), body: NSLocalizedString("Sometimes life hits you in the head with a brick. Don't lose faith.", comment: "Quote"), identifier: 78),
        Quote(author: NSLocalizedString("Charles Swindon", comment: "Author"), body: NSLocalizedString("Life is 10 percent what happens to you and 90 percent how you respond to it.", comment: "Quote"), identifier: 79),
        Quote(author: NSLocalizedString("Eleanor Roosevelt", comment: "Author"), body: NSLocalizedString("If life were predictable it would cease to be life, and be without flavour.", comment: "Quote"), identifier: 80),
        Quote(author: NSLocalizedString("Robert H. Schuller", comment: "Author"), body: NSLocalizedString("Tough times don’t last. Tough people do.", comment: "Body"), identifier: 81),
        Quote(author: NSLocalizedString("motivationping.com", comment: "Author"), body: NSLocalizedString("Keep going. Everything you need will come to you at the perfect time.", comment: "Body"), identifier: 82),
        Quote(author: NSLocalizedString("motivationping.com", comment: "Author"), body: NSLocalizedString("You have to be at your strongest when you’re feeling at your weakest.", comment: "Body"), identifier: 83),
        Quote(author: NSLocalizedString("motivationping.com", comment: "Author"), body: NSLocalizedString("Never give up. Great things take time. Be patient.", comment: "Body"), identifier: 84),
        Quote(author: NSLocalizedString("Confucius", comment: "Author"), body: NSLocalizedString("It does not matter how slowly you go as long as you do not stop.", comment: "Body"), identifier: 85),
        Quote(author: NSLocalizedString("motivationping.com", comment: "Author"), body: NSLocalizedString("If you feel like giving up, just look back on how far you are already.", comment: "Body"), identifier: 86),
        Quote(author: NSLocalizedString("Kenji Miyazawa", comment: "Author"), body: NSLocalizedString("We must embrace pain and burn it as fuel for our journey.", comment: "Body"), identifier: 87),
        Quote(author: NSLocalizedString("Duke Ellington", comment: "Author"), body: NSLocalizedString("A problem is a chance for you to do your best.", comment: "Body"), identifier: 88),
        Quote(author: NSLocalizedString("Bob Riley", comment: "Author"), body: NSLocalizedString("Hard times don’t create heroes. It is during the hard times when the ‘hero’ within us is revealed.", comment: "Body"), identifier: 89),
        Quote(author: NSLocalizedString("Jillian Michaels", comment: "Author"), body: NSLocalizedString("It’s not about perfect. It’s about effort.", comment: "Body"), identifier: 90),
        Quote(author: NSLocalizedString("Theodore Roosevelt", comment: "Author"), body: NSLocalizedString("Believe you can and you’re halfway there.", comment: "Body"), identifier: 91),
        Quote(author: NSLocalizedString("John Tew", comment: "Author"), body: NSLocalizedString("You are so much more than what you are going through.", comment: "Body"), identifier: 92),
        Quote(author: NSLocalizedString("Holy Holm", comment: "Author"), body: NSLocalizedString("Passion first and everything will fall into place.", comment: "Body"), identifier: 93),
        Quote(author: NSLocalizedString("Zig Ziglar", comment: "Author"), body: NSLocalizedString("Difficult roads always lead to beautiful destinations.", comment: "Body"), identifier: 94),
        Quote(author: NSLocalizedString("Unknown", comment: "Author"), body: NSLocalizedString("Staying positive does not mean that things will turn out okay. Rather it is knowing that you will be okay no matter how things turn out.", comment: "Body"), identifier: 95),
        Quote(author: NSLocalizedString("motivationping.com", comment: "Author"), body: NSLocalizedString("Success is what happens after you have survived all of your disappointments.", comment: "Body"), identifier: 96),
        Quote(author: NSLocalizedString("John Maxwell", comment: "Author"), body: NSLocalizedString("Goals may give focus, but dreams give power.", comment: "Body"), identifier: 97),
        Quote(author: NSLocalizedString("Christopher Reeve", comment: "Author"), body: NSLocalizedString("Once you choose hope, anything’s possible.", comment: "Body"), identifier: 98),
        Quote(author: NSLocalizedString("Plato", comment: "Author"), body: NSLocalizedString("The first and greatest victory is to conquer self.", comment: "Body"), identifier: 99),
        Quote(author: NSLocalizedString("Marcus Garvey", comment: "Author"), body: NSLocalizedString("With confidence you have won before you have started.", comment: "Body"), identifier: 100),
        Quote(author: NSLocalizedString("Luis Galarza", comment: "Author"), body: NSLocalizedString("Success is what comes after you stop making excuses.", comment: "Quote"), identifier: 101),
        Quote(author: NSLocalizedString("J.M. Barrie", comment: "Author"), body: NSLocalizedString("The moment you doubt whether you can fly, you cease for ever to be able to do it.", comment: "Quote"), identifier: 102),
        Quote(author: NSLocalizedString("Steve Martin", comment: "Author"), body: NSLocalizedString("Be so good they can’t ignore you.", comment: "Quote"), identifier: 103),
        Quote(author: NSLocalizedString("Jim Rohn", comment: "Author"), body: NSLocalizedString("When you know what you want, and want it bad enough, you’ll find a way to get it.", comment: "Quote"), identifier: 104),
        Quote(author: NSLocalizedString("Swati Sharma", comment: "Author"), body: NSLocalizedString("The best way to gain self-confidence is to do what you are afraid to do.", comment: "Quote"), identifier: 105),
        Quote(author: NSLocalizedString("Jim Rohn", comment: "Author"), body: NSLocalizedString("Motivation is what gets you started. Habit is what keeps you going.", comment: "Quote"), identifier: 106),
        Quote(author: NSLocalizedString("Confucius", comment: "Author"), body: NSLocalizedString("Our greatest glory is not in never falling, but in rising every time we fall.", comment: "Quote"), identifier: 107),
        Quote(author: NSLocalizedString("Arthur Ashe", comment: "Author"), body: NSLocalizedString("Start where you are. Use what you have. Do what you can.", comment: "Quote"), identifier: 108),
        Quote(author: NSLocalizedString("Mahatma Gandhi", comment: "Author"), body: NSLocalizedString("Strength does not come from physical capacity. It comes from an indomitable will.", comment: "Quote"), identifier: 109),
        Quote(author: NSLocalizedString("Art Williams", comment: "Author"), body: NSLocalizedString("I’m not telling you it is going to be easy, I’m telling you it’s going to be worth it.", comment: "Quote"), identifier: 110),
        Quote(author: NSLocalizedString("Aristotle Onassis", comment: "Author"), body: NSLocalizedString("It is during our darkest moments that we must focus to see the light.", comment: "Quote"), identifier: 111),
        Quote(author: NSLocalizedString("Vince Lombardi", comment: "Author"), body: NSLocalizedString("Perfection is not attainable, but if we chase perfection we can catch excellence.", comment: "Quote"), identifier: 112),
        Quote(author: NSLocalizedString("Rikki Rogers", comment: "Author"), body: NSLocalizedString("Strength doesn’t come from what you can do. It comes from overcoming the things you once thought you couldn’t.", comment: "Quote"), identifier: 113),
        Quote(author: NSLocalizedString("Muhammad Ali", comment: "Author"), body: NSLocalizedString("He who is not courageous enough to take risks will accomplish nothing in life.", comment: "Quote"), identifier: 114),
        Quote(author: NSLocalizedString("Barbara De Angelis", comment: "Author"), body: NSLocalizedString("We don’t develop courage by being happy every day. We develop it by surviving difficult times and challenging adversity.", comment: "Quote"), identifier: 115),
        Quote(author: NSLocalizedString("Nelson Mandela", comment: "Author"), body: NSLocalizedString("I learned that courage was not the absence of fear, but the triumph over it. The brave man is not he who does not feel afraid, but he who conquers that fear.", comment: "Quote"), identifier: 116),
        Quote(author: NSLocalizedString("Walt Disney", comment: "Author"), body: NSLocalizedString("All our dreams can come true, if we have the courage to pursue them.", comment: "Quote"), identifier: 117),
        Quote(author: NSLocalizedString("Ralph Waldo Emerson", comment: "Author"), body: NSLocalizedString("The only person you are destined to become is the person you decide to be.", comment: "Quote"), identifier: 118),
        Quote(author: NSLocalizedString("William James", comment: "Author"), body: NSLocalizedString("Pessimism leads to weakness, optimism to power.", comment: "Quote"), identifier: 119),
        Quote(author: NSLocalizedString("Unknown", comment: "Author"), body: NSLocalizedString("The struggle you’re in today is developing the strength you need for tomorrow.", comment: "Quote"), identifier: 120),
        Quote(author: NSLocalizedString("Henry Rollins", comment: "Author"), body: NSLocalizedString("Strength is the product of struggle. You must do what others don’t to achieve what others won't.", comment: "Quote"), identifier: 121),
        Quote(author: NSLocalizedString("Unknown", comment: "Author"), body: NSLocalizedString("Don’t think about what might go wrong. Think about what might go right.", comment: "Quote"), identifier: 122),
        Quote(author: NSLocalizedString("Roy T. Bennett", comment: "Author"), body: NSLocalizedString("Your hardest times often lead to the greatest moments of your life. Keep going. Tough situations build strong people in the end.", comment: "Quote"), identifier: 123),
        Quote(author: NSLocalizedString("Unknown", comment: "Author"), body: NSLocalizedString("You have to fight through some bad days to earn the best days of your life.", comment: "Quote"), identifier: 124),
        Quote(author: NSLocalizedString("E.E. Cummings", comment: "Author"), body: NSLocalizedString("It takes courage to grow up and become who you really are.", comment: "Quote"), identifier: 125),
        Quote(author: NSLocalizedString("Unknown", comment: "Author"), body: NSLocalizedString("Every next level of your life will demand a different version of you.", comment: "Quote"), identifier: 126),
        Quote(author: NSLocalizedString("Shalane Flanagan", comment: "Author"), body: NSLocalizedString("Don’t let your fear decide your future.", comment: "Quote"), identifier: 127),
        Quote(author: NSLocalizedString("Steve Maraboli", comment: "Author"), body: NSLocalizedString("You were put on this Earth to achieve your greatest self, to live out your purpose, and to do it courageously.", comment: "Quote"), identifier: 128),
        Quote(author: NSLocalizedString("Franklin D. Roosevelt", comment: "Author"), body: NSLocalizedString("The future belongs to those who believe in the beauty of their dreams.", comment: "Quote"), identifier: 129),
        Quote(author: NSLocalizedString("John Assaraf", comment: "Author"), body: NSLocalizedString("Don’t downgrade your dream just to fit your reality. Upgrade your conviction to match your destiny.", comment: "Quote"), identifier: 130),
        Quote(author: NSLocalizedString("Roy T. Bennett", comment: "Author"), body: NSLocalizedString("Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", comment: "Quote"), identifier: 131),
        Quote(author: NSLocalizedString("Joel Osteen", comment: "Author"), body: NSLocalizedString("Choosing to be positive and having a grateful attitude is going to determine how you’re going to live your life.", comment: "Quote"), identifier: 132),
        Quote(author: NSLocalizedString("Wayne Dyer", comment: "Author"), body: NSLocalizedString("If you believe it will work out, you’ll see opportunities. If you believe it won’t, you will see obstacles.", comment: "Quote"), identifier: 133),
        Quote(author: NSLocalizedString("Anne Wilson Schaef", comment: "Author"), body: NSLocalizedString("Life is a process. We are a process. The universe is a process.", comment: "Quote"), identifier: 134),
        Quote(author: NSLocalizedString("Anaïs Nin", comment: "Author"), body: NSLocalizedString("Life shrinks or expands in proportion to one’s courage.", comment: "Quote"), identifier: 135),
        Quote(author: NSLocalizedString("Stephen King", comment: "Author"), body: NSLocalizedString("The scariest moment is always just before you start.", comment: "Quote"), identifier: 136),
        Quote(author: NSLocalizedString("J. R. R. Tolkien", comment: "Author"), body: NSLocalizedString("Little by little, one travels far.", comment: "Quote"), identifier: 137),
        Quote(author: NSLocalizedString("Walt Whitman", comment: "Author"), body: NSLocalizedString("I exist as I am, that is enough.", comment: "Quote"), identifier: 138),
        Quote(author: NSLocalizedString("William Shakespeare", comment: "Author"), body: NSLocalizedString("We know what we are, but know not what we may be.", comment: "Quote"), identifier: 139),
        Quote(author: NSLocalizedString("Franz Kafka", comment: "Author"), body: NSLocalizedString("Paths are made by walking.", comment: "Quote"), identifier: 140),
        Quote(author: NSLocalizedString("Oscar Wilde", comment: "Author"), body: NSLocalizedString("We are all in the gutter, but some of us are looking at the stars.", comment: "Quote"), identifier: 141),
        Quote(author: NSLocalizedString("Albert Einstein", comment: "Author"), body: NSLocalizedString("We have to do the best we are capable of. This is our sacred human responsibility.", comment: "Quote"), identifier: 142),
        Quote(author: NSLocalizedString("Dan Brown", comment: "Author"), body: NSLocalizedString("Everything is possible. The impossible just takes longer.", comment: "Quote"), identifier: 143),
        Quote(author: NSLocalizedString("Robert Frost", comment: "Author"), body: NSLocalizedString("Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.", comment: "Quote"), identifier: 144),
        Quote(author: NSLocalizedString("Toni Morrison", comment: "Author"), body: NSLocalizedString("If you are free, you need to free somebody else. If you have some power, then your job is to empower somebody else.", comment: "Quote"), identifier: 145),
        Quote(author: NSLocalizedString("William Shakespeare", comment: "Author"), body: NSLocalizedString("It is not in the stars to hold our destiny but in ourselves.", comment: "Quote"), identifier: 146),
        Quote(author: NSLocalizedString("Jim Rohn", comment: "Author"), body: NSLocalizedString("If you are not willing to risk the unusual, you will have to settle for the ordinary.", comment: "Quote"), identifier: 147),
        Quote(author: NSLocalizedString("Neil Strauss", comment: "Author"), body: NSLocalizedString("Great things never came from comfort zones.", comment: "Quote"), identifier: 148),
        Quote(author: NSLocalizedString("Thomas Jefferson", comment: "Author"), body: NSLocalizedString("If you want something you never had, you have to do something you’ve never done.", comment: "Quote"), identifier: 149),
        Quote(author: NSLocalizedString("Joe Dispenza", comment: "Author"), body: NSLocalizedString("You are the person you have been waiting for.", comment: "Quote"), identifier: 150),
        Quote(author: NSLocalizedString("Maxime Légace", comment: "Author"), body: NSLocalizedString("The easiest way to change the world is to change yourself.", comment: "Quote"), identifier: 151),
        Quote(author: NSLocalizedString("Winston Churchill", comment: "Author"), body: NSLocalizedString("The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", comment: "Quote"), identifier: 152),
        Quote(author: NSLocalizedString("Unknown", comment: "Author"), body: NSLocalizedString("You learn more from failure than from success. don’t let it stop you. Failure builds character.", comment: "Quote"), identifier: 153),
        Quote(author: NSLocalizedString("Steve Jobs", comment: "Author"), body: NSLocalizedString("If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.", comment: "Quote"), identifier: 154),
        Quote(author: NSLocalizedString("Johann Wolfgang Von Goethe", comment: "Author"), body: NSLocalizedString("Knowing is not enough; we must apply. wishing is not enough; we must do.", comment: "Quote"), identifier: 155),
        Quote(author: NSLocalizedString("Brian Tracy", comment: "Author"), body: NSLocalizedString("Imagine your life is perfect in every respect; what would it look like?", comment: "Quote"), identifier: 156),
        Quote(author: NSLocalizedString("Helen Keller", comment: "Author"), body: NSLocalizedString("Security is mostly a superstition. Life is either a daring adventure or nothing.", comment: "Quote"), identifier: 157),
        Quote(author: NSLocalizedString("Hasidic Proverb", comment: "Author"), body: NSLocalizedString("The man who has confidence in himself gains the confidence of others.", comment: "Quote"), identifier: 158),
        Quote(author: NSLocalizedString("Albert Einstein", comment: "Author"), body: NSLocalizedString("Creativity is intelligence having fun.", comment: "Quote"), identifier: 159),
        Quote(author: NSLocalizedString("Don Zimmer", comment: "Author"), body: NSLocalizedString("What you lack in talent can be made up with desire, hustle and giving 110% all the time.", comment: "Quote"), identifier: 160),
        Quote(author: NSLocalizedString("Theodore Roosevelt", comment: "Author"), body: NSLocalizedString("Do what you can with all you have, wherever you are.", comment: "Quote"), identifier: 161),
        Quote(author: NSLocalizedString("Brian Tracy", comment: "Author"), body: NSLocalizedString("Develop an 'attitude of gratitude'. Say thank you to everyone you meet for everything they do for you.", comment: "Quote"), identifier: 162),
        Quote(author: NSLocalizedString("Confucius", comment: "Author"), body: NSLocalizedString("To see what is right and not do it is a lack of courage.", comment: "Quote"), identifier: 163),
        Quote(author: NSLocalizedString("Brian Tracey", comment: "Author"), body: NSLocalizedString("Reading is to the mind, as exercise is to the body.", comment: "Quote"), identifier: 164),
        Quote(author: NSLocalizedString("Jack Canfield", comment: "Author"), body: NSLocalizedString("For every reason it's not possible, there are hundreds of people who have faced the same circumstances and succeeded.", comment: "Quote"), identifier: 165),
        Quote(author: NSLocalizedString("Marcus Tullius Cicero", comment: "Author"), body: NSLocalizedString("A room without books is like a body without a soul.", comment: "Quote"), identifier: 166),
        Quote(author: NSLocalizedString("Michael Phelps", comment: "Author"), body: NSLocalizedString("I think goals should never be easy, they chould force you to work, even if they are uncomfortable at the time.", comment: "Quote"), identifier: 167),
        Quote(author: NSLocalizedString("Robert H. Schuller", comment: "Author"), body: NSLocalizedString("Today's accomplishments were yesterday's impossibilities.", comment: "Quote"), identifier: 168),
        Quote(author: NSLocalizedString("Steve Jobs", comment: "Author"), body: NSLocalizedString("The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.", comment: "Quote"), identifier: 169),
        Quote(author: NSLocalizedString("Brian Tracy", comment: "Author"), body: NSLocalizedString("A clear vision, backed by definite plans, gives you a tremendous feeling of confidence and personal power.", comment: "Quote"), identifier: 170),
        Quote(author: NSLocalizedString("Brian Tracy", comment: "Author"), body: NSLocalizedString("There are no limits on what you can accomplish, except the limits you place on your own thinking.", comment: "Quote"), identifier: 171),
        Quote(author: NSLocalizedString("William James", comment: "Author"), body: NSLocalizedString("Act as if what you do makes a difference. It does.", comment: "Quote"), identifier: 172),
        Quote(author: NSLocalizedString("Helen Keller", comment: "Author"), body: NSLocalizedString("Never bend your head. Always hold it high. Look the world straight in the eye.", comment: "Quote"), identifier: 173),
        Quote(author: NSLocalizedString("Zig Ziglar", comment: "Author"), body: NSLocalizedString("What you get by acheiving your goals is not as important as what you become by acheiving your goals.", comment: "Quote"), identifier: 174),
        Quote(author: NSLocalizedString("Carol Burnett", comment: "Author"), body: NSLocalizedString("When you have a dream, you've got to grab it and never let go.", comment: "Quote"), identifier: 175),
        Quote(author: NSLocalizedString("Jimmy Dean", comment: "Author"), body: NSLocalizedString("I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", comment: "Quote"), identifier: 176),
        Quote(author: NSLocalizedString("Demi Lovato", comment: "Author"), body: NSLocalizedString("No matter what you're going through, there's light at the end of the tunnel.", comment: "Quote"), identifier: 177),
        Quote(author: NSLocalizedString("William James", comment: "Author"), body: NSLocalizedString("It is our attitude at the beginning of a difficult task which, more than anything else, will affect its successful outcome.", comment: "Quote"), identifier: 178),
        Quote(author: NSLocalizedString("Amy Poehler​​", comment: "Author"), body: NSLocalizedString("Limit your 'always' and your 'nevers.'", comment: "Quote"), identifier: 179),
        Quote(author: NSLocalizedString("Camilla Eyring Kimball", comment: "Author"), body: NSLocalizedString("You do not find the happy life. You make it.", comment: "Quote"), identifier: 180),
        Quote(author: NSLocalizedString("Dr Seuss", comment: "Author"), body: NSLocalizedString("Sometimes you will never know the value of a moment, until it becomes a memory.", comment: "Quote"), identifier: 181),
        Quote(author: NSLocalizedString("E. E. Cummings", comment: "Author"), body: NSLocalizedString("The most wasted of days is one without laughter.", comment: "Quote"), identifier: 182),
        Quote(author: NSLocalizedString("Hafez", comment: "Author"), body: NSLocalizedString("Stay close to anything that makes you glad you are alive.", comment: "Quote"), identifier: 183),
        Quote(author: NSLocalizedString("Jennifer Lopez", comment: "Author"), body: NSLocalizedString("You get what you give.", comment: "Quote"), identifier: 184),
        Quote(author: NSLocalizedString("Jim Rohn", comment: "Author"), body: NSLocalizedString("Happiness is not by chance, but by choice.", comment: "Quote"), identifier: 185),
        Quote(author: NSLocalizedString("Maya Angelou", comment: "Author"), body: NSLocalizedString("My mission in life is not merely to survive, but to thrive.", comment: "Quote"), identifier: 186),
        Quote(author: NSLocalizedString("Quentin Blake", comment: "Author"), body: NSLocalizedString("Inspiration is some mysterious blessing which happens when the wheels are turning smoothly.", comment: "Quote"), identifier: 187),
        Quote(author: NSLocalizedString("Rosa Parks", comment: "Author"), body: NSLocalizedString("Each person must live their life as a model for others.", comment: "Quote"), identifier: 188),
        Quote(author: NSLocalizedString("Sheryl Sandberg", comment: "Author"), body: NSLocalizedString("Motivation comes from working on things we care about.", comment: "Quote"), identifier: 189),
        Quote(author: NSLocalizedString("Joyce Meyer", comment: "Author"), body: NSLocalizedString("You only have one life, and if it is not going in the direction you want it to, now is the time to make changes.", comment: "Quote"), identifier: 190),
        Quote(author: NSLocalizedString("Mark Dudley", comment: "Author"), body: NSLocalizedString("Never let your past decisions determine your future outcome.", comment: "Quote"), identifier: 191),
        Quote(author: NSLocalizedString("Paul Brodie", comment: "Author"), body: NSLocalizedString("Our character is not defined in the good times, but in the hard times. ", comment: "Quote"), identifier: 192),
        Quote(author: NSLocalizedString("Brad Sugars", comment: "Author"), body: NSLocalizedString("Words can inspire, thoughts can provoke, but only action truly brings you closer to your dreams.", comment: "Quote"), identifier: 193),
        Quote(author: NSLocalizedString("Paul Dalton", comment: "Author"), body: NSLocalizedString("Inspiration is a message from your unconscious wisdom telling you to go out there and be the fullest, most positive expression of you who you REALLY are.", comment: "Quote"), identifier: 194),
        Quote(author: NSLocalizedString("Dr. Irene C. Kassorla", comment: "Author"), body: NSLocalizedString("Quitters never win. Winners never quit!", comment: "Quote"), identifier: 195),
        Quote(author: NSLocalizedString("Vishal Pandey", comment: "Author"), body: NSLocalizedString("Everyone has the potential to live a fulfilling life. The difference lies in how we look at things.", comment: "Quote"), identifier: 196),
        Quote(author: NSLocalizedString("Robyn Pearce", comment: "Author"), body: NSLocalizedString("There's no such thing as lack of time, only lack of focus. We can all do the things we really want to do.", comment: "Quote"), identifier: 197),
        Quote(author: NSLocalizedString("Amy Torres", comment: "Author"), body: NSLocalizedString("Life without purpose is meaningless.", comment: "Quote"), identifier: 198),
        Quote(author: NSLocalizedString("Wayne Huizenga", comment: "Author"), body: NSLocalizedString("Some people dream of success, while other people get up every morning and make it happen.", comment: "Quote"), identifier: 199),
        Quote(author: NSLocalizedString("Bill Bradley", comment: "Author"), body: NSLocalizedString("Ambition is the path to success. Persistence is the vehicle you arrive in.", comment: "Quote"), identifier: 200),
        Quote(author: NSLocalizedString("Kam Knight", comment: "Author"), body: NSLocalizedString("...goals allow you to take control. Instead of living life by chance, you live by choice.", comment: "Quote"), identifier: 201),
        Quote(author: NSLocalizedString("Becca Earl", comment: "Author"), body: NSLocalizedString("If you've set goals and you want to achieve them, you have to think positively and achieving those goals will be a lot easier.", comment: "Quote"), identifier: 202),
        Quote(author: NSLocalizedString("Tony Dingy", comment: "Author"), body: NSLocalizedString("Remember to focus on goals that are within your control.", comment: "Quote"), identifier: 203),
        Quote(author: NSLocalizedString("Yiddish Proverb", comment: "Author"), body: NSLocalizedString("The truly rich are those who enjoy what they have.", comment: "Quote"), identifier: 204),
        Quote(author: NSLocalizedString("Eric Thomas", comment: "Author"), body: NSLocalizedString("You gotta stay hungry! Stay focused! And you better have heart! The heart of a champion!", comment: "Quote"), identifier: 205),
        Quote(author: NSLocalizedString("Eric Thomas", comment: "Author"), body: NSLocalizedString("For every dream that you have, your week needs to match that dream.", comment: "Quote"), identifier: 206),
        Quote(author: NSLocalizedString("Michelle Obama", comment: "Author"), body: NSLocalizedString("Instead of letting your hardships and failures discourage or exhaust you, let them inspire you.", comment: "Quote"), identifier: 207),
        Quote(author: NSLocalizedString("Benjamin Franklin", comment: "Author"), body: NSLocalizedString("Wink at small faults; remember thou hast great ones.", comment: "Quote"), identifier: 208),
        Quote(author: NSLocalizedString("Albert Einstein", comment: "Author"), body: NSLocalizedString("Failure is success in progress.", comment: "Quote"), identifier: 209),
        Quote(author: NSLocalizedString("Nelson Mandela", comment: "Author"), body: NSLocalizedString("It always seems impossible until it's done.", comment: "Quote"), identifier: 210),
        Quote(author: NSLocalizedString("Mark Twain", comment: "Author"), body: NSLocalizedString("Every person is a book, each year a chapter.", comment: "Quote"), identifier: 211),
        Quote(author: NSLocalizedString("Charlie Day", comment: "Author"), body: NSLocalizedString("You cannot let a fear of failure or a fear of comparison or a fear of judgment stop you from doing what's going to make you great.", comment: "Quote"), identifier: 212),
        Quote(author: NSLocalizedString("Thomas Edison", comment: "Author"), body: NSLocalizedString("Your worth consists in what you are and not in what you have.", comment: "Quote"), identifier: 213),
        Quote(author: NSLocalizedString("Catherine Pulsifer", comment: "Author"), body: NSLocalizedString("Don't focus on regrets; find your inspiration in what you can do now.", comment: "Quote"), identifier: 214),
        Quote(author: NSLocalizedString("James O. Prochaska", comment: "Author"), body: NSLocalizedString("Although we cannot intentionally change many aspects of ourselves or our world, we can exert some power over the courses of our own lives.", comment: "Quote"), identifier: 215),
        Quote(author: NSLocalizedString("Karen Flaherty", comment: "Author"), body: NSLocalizedString("You are who you are, and nothing can change that. You're beautiful just as you are.", comment: "Quote"), identifier: 216),
        Quote(author: NSLocalizedString("Debbie Macomber", comment: "Author"), body: NSLocalizedString("Yes, indeed, one word of encouragement can change the world.", comment: "Quote"), identifier: 217),
        Quote(author: NSLocalizedString("Simeon Lindstrom", comment: "Author"), body: NSLocalizedString("Like many things in life, your compassion is a skill that can be exercised.", comment: "Quote"), identifier: 218),
        Quote(author: NSLocalizedString("Roald Dahl", comment: "Author"), body: NSLocalizedString("Never do anything by halves if you want to get away with it. Be outrageous. Go the whole hog.", comment: "Quote"), identifier: 219),
        Quote(author: NSLocalizedString("Roald Dahl", comment: "Author"), body: NSLocalizedString("We are the music makers, and we are the dreamers of dreams.", comment: "Quote"), identifier: 220),
        Quote(author: NSLocalizedString("Roald Dahl", comment: "Author"), body: NSLocalizedString("If you are good, life is good.", comment: "Quote"), identifier: 221),
        Quote(author: NSLocalizedString("Roald Dahl", comment: "Author"), body: NSLocalizedString("I understand what you’re saying, and your comments are valuable, but I’m gonna ignore your advice.", comment: "Quote"), identifier: 222),
        Quote(author: NSLocalizedString("Roald Dahl", comment: "Author"), body: NSLocalizedString("A little magic can take you a long way.", comment: "Quote"), identifier: 223),
        Quote(author: NSLocalizedString("Roald Dahl", comment: "Author"), body: NSLocalizedString("Most of the really exciting things we do in our lives scare us to death. They wouldn’t be exciting if they didn’t.", comment: "Quote"), identifier: 224),
        Quote(author: NSLocalizedString("Roald Dahl", comment: "Author"), body: NSLocalizedString("Having power is not nearly as important as what you choose to do with it.", comment: "Quote"), identifier: 225),
        Quote(author: NSLocalizedString("Roald Dahl", comment: "Author"), body: NSLocalizedString("Life is more fun if you play games.", comment: "Quote"), identifier: 226),
        Quote(author: NSLocalizedString("Nelson Mandela", comment: "Author"), body: NSLocalizedString("There is no passion to be found playing small - in settling for a life that is less than the one you are capable of living.", comment: "Quote"), identifier: 227),
        Quote(author: NSLocalizedString("Nelson Mandela", comment: "Author"), body: NSLocalizedString("As we let our own light shine, we unconsciously give other people permission to do the same.", comment: "Quote"), identifier: 228),
        Quote(author: NSLocalizedString("Nelson Mandela", comment: "Author"), body: NSLocalizedString("A winner is a dreamer who never gives up", comment: "Quote"), identifier: 229),
        Quote(author: NSLocalizedString("Michelle Obama", comment: "Author"), body: NSLocalizedString("Your story is what you have, what you will always have. It is something to own,", comment: "Quote"), identifier: 230),
        Quote(author: NSLocalizedString("Michelle Obama", comment: "Author"), body: NSLocalizedString("If there's one thing I've learned in life, it's the power of using your voice,", comment: "Quote"), identifier: 231),
        Quote(author: NSLocalizedString("Michelle Obama", comment: "Author"), body: NSLocalizedString("Don’t ever make decisions based on fear. Make decisions based on hope and possibility. Make decisions based on what should happen, not what shouldn’t,", comment: "Quote"), identifier: 232),
        Quote(author: NSLocalizedString("Barack Obama", comment: "Author"), body: NSLocalizedString("The future rewards those who press on. I don't have time to feel sorry for myself. I don't have time to complain. I'm going to press on.", comment: "Quote"), identifier: 233),
        Quote(author: NSLocalizedString("Barack Obama", comment: "Author"), body: NSLocalizedString("If you're walking down the right path and you're willing to keep walking, eventually you'll make progress.", comment: "Quote"), identifier: 234),
        Quote(author: NSLocalizedString("Barack Obama", comment: "Author"), body: NSLocalizedString("If you're walking down the right path and you're willing to keep walking, eventually you'll make progress.", comment: "Quote"), identifier: 235),
        Quote(author: NSLocalizedString("Ollin Miller", comment: "Author"), body: NSLocalizedString("You wouldn’t worry so much about what others think of you if you realized how seldom they do.", comment: "Quote"), identifier: 236),
        Quote(author: NSLocalizedString("Shannon L. Alder", comment: "Author"), body: NSLocalizedString("He who is not everyday conquering some fear has not learned the secret of life.", comment: "Quote"), identifier: 237),
        Quote(author: NSLocalizedString("Jacqueline Whitney", comment: "Author"), body: NSLocalizedString("Hey you, keep living. It won’t always be this overwhelming.", comment: "Quote"), identifier: 238),
        Quote(author: NSLocalizedString("Etty Hillesum", comment: "Author"), body: NSLocalizedString("Sometimes the most important thing in a whole day is the rest taken between two deep breaths.", comment: "Quote"), identifier: 239),
        Quote(author: NSLocalizedString("Robert Eliot", comment: "Author"), body: NSLocalizedString("Rule number one is, don’t sweat the small stuff. Rule number two is, it’s all small stuff.", comment: "Quote"), identifier: 240),
        Quote(author: NSLocalizedString("William S. Burroughs", comment: "Author"), body: NSLocalizedString("Your mind will answer most questions if you learn to relax and wait for the answer.", comment: "Quote"), identifier: 241),
        Quote(author: NSLocalizedString("Lily Tomlin", comment: "Author"), body: NSLocalizedString("For fast acting relief, try slowing down.", comment: "Quote"), identifier: 242),
        Quote(author: NSLocalizedString("Wayne W. Dyer", comment: "Author"), body: NSLocalizedString("Peace is the result of retraining your mind to process life as it is, rather than as you think it should be.", comment: "Quote"), identifier: 243),
        Quote(author: NSLocalizedString("Paulo Coelho", comment: "Author"), body: NSLocalizedString("Anxiety was born in the very same moment as mankind. And since we will never be able to master it, we will have to learn to live with it—just as we have learned to live with storms.", comment: "Quote"), identifier: 244),
        Quote(author: NSLocalizedString("Ralph Waldo Emerson", comment: "Author"), body: NSLocalizedString("Nothing can bring you peace but yourself.", comment: "Quote"), identifier: 245),
        Quote(author: NSLocalizedString("Robert Tew", comment: "Author"), body: NSLocalizedString("Trust yourself. You’ve survived a lot, and you’ll survive whatever is coming.", comment: "Quote"), identifier: 246),
        Quote(author: NSLocalizedString("Sonia Ricotte", comment: "Author"), body: NSLocalizedString("Surrender to what is. Let go of what was. Have faith in what will be.", comment: "Quote"), identifier: 247),
        Quote(author: NSLocalizedString("Pema Chodron", comment: "Author"), body: NSLocalizedString("If we learn to open our hearts, anyone, including the people who drive us crazy, can be our teacher.", comment: "Quote"), identifier: 248),
        Quote(author: NSLocalizedString("Heather Stillufsen", comment: "Author"), body: NSLocalizedString("Keep walking through the storm. Your rainbow is waiting on the other side.", comment: "Quote"), identifier: 249),
        Quote(author: NSLocalizedString("Chris Butler", comment: "Author"), body: NSLocalizedString("Today’s a perfect day for a whole new start. Let go of fear and free your mind. It’s time to open your heart.", comment: "Quote"), identifier: 250),
        Quote(author: NSLocalizedString("Jim Rohn", comment: "Author"), body: NSLocalizedString("Happiness is not something you postpone for the future; it is something you design for the present.", comment: "Quote"), identifier: 251),
        Quote(author: NSLocalizedString("Saadi", comment: "Author"), body: NSLocalizedString("Have patience. All things are difficult before they become easy.", comment: "Quote"), identifier: 252),
        Quote(author: NSLocalizedString("Michelle C. Ustaszeski", comment: "Author"), body: NSLocalizedString("Before you can consider a problem water under the bridge, you must first patiently work on removing the dam.", comment: "Quote"), identifier: 253),
        Quote(author: NSLocalizedString("Edmund Burke", comment: "Author"), body: NSLocalizedString("Our patience will achieve more than our force.", comment: "Quote"), identifier: 254),
        Quote(author: NSLocalizedString("Catherine Pulsifer", comment: "Author"), body: NSLocalizedString("Learning patience can be a difficult experience, but once conquered you will find life is easier.", comment: "Quote"), identifier: 255),
        Quote(author: NSLocalizedString("Edward G. Bulwer-Lytton", comment: "Author"), body: NSLocalizedString("Patience is not passive; on the contrary, it is active; it is concentrated strength.", comment: "Quote"), identifier: 256),
        Quote(author: NSLocalizedString("Norman Vincent Peale", comment: "Author"), body: NSLocalizedString("Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.", comment: "Quote"), identifier: 257),
        Quote(author: NSLocalizedString("Samuel Taylor Coleridge", comment: "Author"), body: NSLocalizedString("Nothing is so contagious as enthusiasm.", comment: "Quote"), identifier: 258),
        Quote(author: NSLocalizedString("Roy Bennett", comment: "Author"), body: NSLocalizedString("Start each day with a positive thought and a grateful heart.", comment: "Quote"), identifier: 259),
        Quote(author: NSLocalizedString("Alexander Zalan", comment: "Author"), body: NSLocalizedString("It doesn’t matter how hard and rough life could be, you’ve a great ability to affect your future and people around you.", comment: "Quote"), identifier: 260),
        Quote(author: NSLocalizedString("Melchor Lim", comment: "Author"), body: NSLocalizedString("When faced with a challenge, your size is not as important as having a strong and tenacious spirit.", comment: "Quote"), identifier: 261),
        Quote(author: NSLocalizedString("Maria Robinson", comment: "Author"), body: NSLocalizedString("Nobody can go back and start a new beginning, but anyone can start today and make a new ending.", comment: "Quote"), identifier: 262),
        Quote(author: NSLocalizedString("Christian Louboutin", comment: "Author"), body: NSLocalizedString("You need to believe in yourself and what you do. Be tenacious and genuine.", comment: "Quote"), identifier: 263),
        Quote(author: NSLocalizedString("Dennis Green", comment: "Author"), body: NSLocalizedString("The secret to success is to start from scratch and keep on scratching.", comment: "Quote"), identifier: 264),
        Quote(author: NSLocalizedString("Ntathu Allen", comment: "Author"), body: NSLocalizedString("Let peace be your middle name.", comment: "Quote"), identifier: 265),
        Quote(author: NSLocalizedString("Mother Teresa", comment: "Author"), body: NSLocalizedString("Peace begins with a smile.", comment: "Quote"), identifier: 266),
        Quote(author: NSLocalizedString("Marcus Tullius Cicero", comment: "Author"), body: NSLocalizedString("The pursuit, even of the best things, ought to be calm and tranquil.", comment: "Quote"), identifier: 267),
        Quote(author: NSLocalizedString("Joyce Meyer", comment: "Author"), body: NSLocalizedString("Remain calm in every situation because peace equals power.", comment: "Quote"), identifier: 268),
        Quote(author: NSLocalizedString("Josiah Gilbert Holland", comment: "Author"), body: NSLocalizedString("There is no royal road to anything. One thing at a time, all things in succession. That which grows fast, withers as rapidly. That which grows slowly, endures.", comment: "Quote"), identifier: 269),
        Quote(author: NSLocalizedString("William James", comment: "Author"), body: NSLocalizedString("Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.", comment: "Quote"), identifier: 270),
        Quote(author: NSLocalizedString("Will Rogers", comment: "Author"), body: NSLocalizedString("Even if you’re on the right track, you’ll get run over if you just sit there.", comment: "Quote"), identifier: 271),
        Quote(author: NSLocalizedString("Sydney Harris", comment: "Author"), body: NSLocalizedString("When I hear somebody sigh, ‘Life is hard,’ I am always tempted to ask, ‘Compared to what?’", comment: "Quote"), identifier: 272),
        Quote(author: NSLocalizedString("Benjamin Disraeli", comment: "Author"), body: NSLocalizedString("Nurture your mind with great thoughts. To believe in the heroic makes heroes.", comment: "Quote"), identifier: 273),
        Quote(author: NSLocalizedString("Mahatma Gandhi", comment: "Author"), body: NSLocalizedString("Look at the sparrows; they do not know what they will do in the next moment. Let us literally live from moment to moment.", comment: "Quote"), identifier: 274),
        Quote(author: NSLocalizedString("Zig Ziglar", comment: "Author"), body: NSLocalizedString("The real opportunity for success lies within the person and not in the job.", comment: "Quote"), identifier: 275),
        Quote(author: NSLocalizedString("Lao Tzu", comment: "Author"), body: NSLocalizedString("When I let go of what I am, I become what I might be.", comment: "Quote"), identifier: 276),
        Quote(author: NSLocalizedString("Winston Churchill", comment: "Author"), body: NSLocalizedString("Courage is the first of human qualities because it is the quality which guarantees all others.", comment: "Quote"), identifier: 277),
        Quote(author: NSLocalizedString("Oliver Wendell Holmes", comment: "Author"), body: NSLocalizedString("The great thing in this world is not so much where you stand, as in what direction you are moving.", comment: "Quote"), identifier: 278),
        Quote(author: NSLocalizedString("Johann Wolfgang Von Goethe", comment: "Author"), body: NSLocalizedString("Live each day as if your life had just begun.", comment: "Quote"), identifier: 279),
        Quote(author: NSLocalizedString("Vince Lombardi", comment: "Author"), body: NSLocalizedString("The difference between a successful person and others is not lack of strength not a lack of knowledge but rather a lack of will.", comment: "Quote"), identifier: 280),
        Quote(author: NSLocalizedString("Jim Rohn", comment: "Author"), body: NSLocalizedString("Either you run the day, or the day runs you.", comment: "Quote"), identifier: 281),
        Quote(author: NSLocalizedString("John F. Kennedy", comment: "Author"), body: NSLocalizedString("If not us, who? If not now, when?", comment: "Quote"), identifier: 282),
        Quote(author: NSLocalizedString("Jack Canfield", comment: "Author"), body: NSLocalizedString("Don’t worry about failures, worry about the chances you miss when you don’t even try.", comment: "Quote"), identifier: 283),
        Quote(author: NSLocalizedString("Carl Bard", comment: "Author"), body: NSLocalizedString("Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending.", comment: "Quote"), identifier: 284),
        Quote(author: NSLocalizedString("Unknown", comment: "Author"), body: NSLocalizedString("Life has two rules: #1 Never quit #2 Always remember rule # 1.", comment: "Quote"), identifier: 285),
        Quote(author: NSLocalizedString("Arthur C. Clarke", comment: "Author"), body: NSLocalizedString("The only way of finding the limits of the possible is by going beyond them into the impossible.", comment: "Quote"), identifier: 286),
        Quote(author: NSLocalizedString("Ralph Waldo Emerson", comment: "Author"), body: NSLocalizedString("Do not go where the path may lead, go instead where there is no path and leave a trail.", comment: "Quote"), identifier: 287),
        Quote(author: NSLocalizedString("Sir Claus Moser", comment: "Author"), body: NSLocalizedString("Education costs money. But then so does ignorance.", comment: "Quote"), identifier: 288),
        Quote(author: NSLocalizedString("Thomas Edison", comment: "Author"), body: NSLocalizedString("Many of life’s failures are experienced by people who did not realize how close they were to success when they gave up.", comment: "Quote"), identifier: 289),
        Quote(author: NSLocalizedString("John Wooden", comment: "Author"), body: NSLocalizedString("Do not let what you cannot do interfere with what you can do.", comment: "Quote"), identifier: 290),
        Quote(author: NSLocalizedString("Unknown", comment: "Author"), body: NSLocalizedString("Rule #1 of life. Do what makes YOU happy.", comment: "Quote"), identifier: 291),
        Quote(author: NSLocalizedString("Babe Ruth", comment: "Author"), body: NSLocalizedString("Every strike brings me closer to the next home run.", comment: "Quote"), identifier: 292),
        Quote(author: NSLocalizedString("Prescott", comment: "Author"), body: NSLocalizedString("An obstacle is often a stepping stone.", comment: "Quote"), identifier: 293),
        Quote(author: NSLocalizedString("Stephen Covey", comment: "Author"), body: NSLocalizedString("I am not a product of my circumstances. I am a product of my decisions.", comment: "Quote"), identifier: 294),
        Quote(author: NSLocalizedString("Martin Luther King Jr.", comment: "Author"), body: NSLocalizedString("Our lives begin to end the day we become silent about things that matter.", comment: "Quote"), identifier: 295),
        Quote(author: NSLocalizedString("Woody Allen", comment: "Author"), body: NSLocalizedString("Eighty percent of success is showing up.", comment: "Quote"), identifier: 296),
        Quote(author: NSLocalizedString("Albert Einstein", comment: "Author"), body: NSLocalizedString("I am thankful for all of those who said NO to me. It’s because of them I’m doing it myself.", comment: "Quote"), identifier: 297),
        Quote(author: NSLocalizedString("Earl Nightingale", comment: "Author"), body: NSLocalizedString("We become what we think about.", comment: "Quote"), identifier: 298),
        Quote(author: NSLocalizedString("Buddha", comment: "Author"), body: NSLocalizedString("The mind is everything. What you think you become.", comment: "Quote"), identifier: 299),
        Quote(author: NSLocalizedString("B. B. Bernstein", comment: "Author"), body: NSLocalizedString("If you are going to spend your life running you might as well be chasing your dreams.", comment: "Quote"), identifier: 300),
        Quote(author: NSLocalizedString("Japanese Proverb", comment: "Author"), body: NSLocalizedString("Vision without action is a daydream. Action without vision is a nightmare.", comment: "Quote"), identifier: 301)
    ]
}


